sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-104.pdf --upload --lsstdoc DMTN-104.tex --env=travis --ltd-product dmtn-104"
env:
  global:
    # LSST the Docs credentials
    - secure: "LLEVkNGkpnYAaM+r+5bP6/RRY1n9ZdmrxQoAgQ9Lu03hYWVWvlxRjz0vAlxtGkaz60LhNood3JlRqjNqElkKenB5vK2RjJg7hQXqqDC/7iab2sX1MLj8kUNrnvM6PcNPaeGDAQ4yukvUaxa7g/fkVRpwhTiyJWeG/48xyqK1JAKAv9mFom6iVkPPUJb8ZZ+S2YfzfgV1p9NcfkrrCrEkdUajhmU2edo3GDkRbsPhUenaqCyyz29wCFBNsIves/b734Mq8p99iuKxc3MgEra8NMJJzFyn4f7oKJld0KQwt9QpfP8NZYsf9vn7WSuWuDvuI625o26G0NVRNN/+G+F2ReTCq2z+h2BZBWiyEM4V6rKWY/4BCHdYDwn0rdutVj24m1amaUnD/YnCyWkPiKt8xtVGjU9l948FRtDA9hL3r6XCOC2KZxFxHzYP7uifYfwDUgdGqNMPUHMkcsaMB47uBe0L2LcKoU2g6a7sJOPm9vC4dLYpNIxbePQkU6nD9RuciLfzg7tEuBzgu1AXoU56JWR21F942bBRM4FBys0fPhDzI9jDlKZFvpuUNBuqgmyQIxe4e5moJR+5sx8EptEYrxnv+ccTvZ/Dkzxe5186f8ed7kBU9kZfDs+VZS+1yTdRg7lNAsPvCNa1pkSYIMsWK3QwxyH5Px5a1VDlXsfDJ24="
    - secure: "tX2R3czURF5A0wlZzbZIYFJ8sQHs7kRvna2wYqtiXpglV4zexF5GRDCCDERZxURYQw7z0OFcU4qGpG1yzQwwHnBflsspck8VxUCGAEKBxzP2XSK5EieV0+X2mTM4HDg8d0UfdniR5E8IzGM9gqGt/s+bUYhCMwIuI3W7Nx2GdbHnSoGT0HTeqg3oeAWoUTkVNh2GEFtQGaEkQcBmPiUYnmPD9vVuHrzZRqvlNxVHYPjmi/P140iSCHBoNaHbHYUFN9jI1vGTnRBTyDqlLxOV6RsuICiQSnjXE/xzTzlXbH8ZK0BSq0+EfbpuivuLubhPj0C1puEBPgOf5fT5tW0tEVQpDMG/+ycd55LFbkOkrRC1C4Y8iFj7fGSU5wuf2cwyrgMBV6R00SwbQf4Oe2tV7JMzSzUzlJ6wsrjuuNnAxua5dd0K1JQoBrkFS0UR58GIYoVavjm1f8wxmY2RNax8avUspICt72z61/+/b9sE5saKvk168uNtCfVr2SFECYEc7a2rf5fFTgWZo1kqPtbBNw/EJb/vH7zQ3CfLcne/wyAKCOSuFnyFx3STfW+sh46B97pW7Mgr6QEyRUd//PrQZJ6eO65GtNOVK6xdab2hTHBNrBLxyTYj7TQ4AIfb5TT3VPw/YkGtmGe2TNSJgJOxONsSN1zbP1xxusdB0wzZiKU="
