name: CI

"on": [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Python install
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends ghostscript graphviz
          python -m pip install --upgrade pip
          python -m pip install "lander<2.0.0"
          python -m pip install -r requirements.txt
      - name: TeX build
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make generate_imgs'
          make crop_pdf_imgs makedots
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make DMTN-104.pdf'
      - name: Landing page upload
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          lander --upload --pdf DMTN-104.pdf --ltd-product dmtn-104 --lsstdoc DMTN-104.tex --extra-downloads trees/Main_mixedLand.pdf trees/Main_portrait.pdf trees/Development_portrait.pdf trees/Development_mixedLand.pdf trees/DM_full.pdf
